import type { HrCompany } from './types';

export const hrCompanies: HrCompany[] = [
  {
    id: 1,
    company: 'Vention',
    focus: 'PL / EU software house',
    email: 'careers@ventionteams.com',
  },
  {
    id: 2,
    company: 'Nextcloud',
    focus: 'DE / EU remote',
    email: 'jobs@nextcloud.com',
  },
  {
    id: 3,
    company: 'Grid Dynamics',
    focus: 'EU / US product eng',
    email: 'jobs@griddynamics.com',
  },
  {
    id: 4,
    company: 'EXANTE',
    focus: 'EU remote (AM-friendly regions)',
    email: 'hiring@exante.eu',
  },
  {
    id: 5,
    company: 'Caple',
    focus: 'Netherlands',
    email: 'hiring@caple.eu',
  },
  {
    id: 6,
    company: 'Merixstudio',
    focus: 'Poland',
    email: 'jobs@merixstudio.com',
  },
  {
    id: 7,
    company: 'SparkEXP',
    focus: 'Poland',
    email: 'careers@sparkexp.com',
  },
  {
    id: 8,
    company: 'Lailio',
    focus: 'Latvia',
    email: 'hr@lailio.com',
  },
  {
    id: 9,
    company: 'Music Vine',
    focus: 'UK',
    email: 'careers@musicvine.com',
  },
  {
    id: 10,
    company: 'Screaming Frog',
    focus: 'UK',
    email: 'careers@screamingfrog.co.uk',
  },
  {
    id: 11,
    company: 'Inframatic',
    focus: 'UK',
    email: 'careers@inframatic.ai',
  },
  {
    id: 12,
    company: 'Bytro',
    focus: 'Germany',
    email: 'jobs@bytro.com',
  },
  {
    id: 13,
    company: 'Bytro',
    focus: 'Germany',
    email: 'careers@bytro.com',
  },
  {
    id: 14,
    company: 'Generic Software',
    focus: 'Germany',
    email: 'jobs@generic.de',
  },
  {
    id: 15,
    company: 'Miray Software',
    focus: 'Germany',
    email: 'apply@miray.de',
  },
  {
    id: 16,
    company: 'XDEV',
    focus: 'Germany',
    email: 'application@xdev-software.de',
  },
  {
    id: 17,
    company: 'Carano Software',
    focus: 'Germany',
    email: 'karriere@carano.de',
  },
  {
    id: 18,
    company: 'Evora IT',
    focus: 'Germany / EU',
    email: 'careers-de@evorait.com',
  },
  {
    id: 19,
    company: 'Exxeta',
    focus: 'Germany / Georgia',
    email: 'myfuture@exxeta.com',
  },
  {
    id: 20,
    company: 'Sigma Software',
    focus: 'PL / EU / UA',
    email: 'team@sigma.software',
  },
  {
    id: 21,
    company: 'Sigma Software',
    focus: 'EU offices',
    email: 'info@sigma.software',
  },
  {
    id: 22,
    company: 'ServiceTitan Armenia',
    focus: 'Armenia',
    email: 'armenia@servicetitan.com',
  },
  {
    id: 23,
    company: 'SoftConstruct',
    focus: 'Armenia',
    email: 'info@softconstruct.com',
  },
  {
    id: 24,
    company: 'Kumpan',
    focus: 'Sweden',
    email: 'nea@kumpan.se',
  },
  {
    id: 25,
    company: 'Acsone',
    focus: 'Belgium / EU',
    email: 'jobs@acsone.eu',
  },
  {
    id: 26,
    company: 'Verita HR (React roles PL)',
    focus: 'Poland',
    email: 'iwona.jagiela@veritahr.com',
  },
  {
    id: 27,
    company: 'Consortia (React recruiter)',
    focus: 'UK / NL',
    email: 'joes@consortia.com',
  },
  {
    id: 28,
    company: 'ServiceTitan TA (AM)',
    focus: 'Armenia',
    email: 'lmuradyan@servicetitan.com',
  },
];
